const SHAPES_SOURCE_PATH = "accord-shacl.ttl";
const GENERATED_MODULE_PATH = "src/shacl/shipped_shapes.ts";

if (import.meta.main) {
  await generateShippedShapesModule();
}

export async function generateShippedShapesModule(): Promise<void> {
  const turtle = await Deno.readTextFile(SHAPES_SOURCE_PATH);
  await Deno.writeTextFile(
    GENERATED_MODULE_PATH,
    renderShippedShapesModule(turtle),
  );
}

export function renderShippedShapesModule(turtle: string): string {
  return `// Generated by \`deno task generate:shipped-shapes\`. Do not edit by hand.

export const SHIPPED_SHAPES_TURTLE =
  ${renderTemplateLiteral(turtle)};
`;
}

function renderTemplateLiteral(value: string): string {
  return `\`${
    value
      .replaceAll("\\", "\\\\")
      .replaceAll("`", "\\`")
      .replaceAll("${", "\\${")
  }\``;
}
